---
title: "Lab 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DT)
```

```{r}
report_03_13_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```

```{r, eval = FALSE}
str(report_03_11_2020)
datatable(report_03_11_2020)

```

## 3/13/2020

```{r, eval = FALSE}
str(report_03_13_2020)

datatable(report_03_13_2020)
```

## 9/13/2020
```{r}
report_09_13_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) 

```

```{r, eval = FALSE}
str(report_09_13_2020)
datatable(report_09_13_2020)
```

```{r, eval = FALSE}
library(DT)
datatable(report_03_13_2020)
datatable(report_09_13_2020)
```


### Exercises Part 1


## 1
```{r}
str(report_03_13_2020)

```

```{r}
str(report_09_13_2020)

```

# 2
```{r}
country_total_03_13 <- report_03_13_2020 %>% 
  group_by(Country_Region) %>% 
summarize(total_confirmed = sum(Confirmed, na.rm = TRUE))
head(country_total_03_13)

```


# 3
``` {r}
US <- report_03_13_2020 %>% 
  filter(Country_Region=="US")
US <- US %>% group_by(Province_State, Confirmed)
summarize(US)
```


# 4

```{r, eval = FALSE}
Death <- report_03_13_2020 %>% 
  arrange(desc(Deaths)) %>% 
  slice(1:10)
view(Death)
```


### Exercises Part 2

# Deaths of Top 10 Countries March 13, 2020
```{r}
top10d <- report_03_13_2020 %>%
  group_by(Country_Region) %>%
  summarize(Confirmed = sum(Confirmed), Deaths = sum(Deaths), min_Deaths = min(Deaths)) %>%
  arrange(desc(min_Deaths)) %>%
  slice(1:10)

ggplot(data = top10d, mapping = aes(x = Country_Region, y = Deaths)) + geom_point()
```

# Confirmed Cases of Top 10 Countries March 13, 2020
```{r}
top10d <- report_03_13_2020 %>%
  group_by(Country_Region) %>%
  summarize(Confirmed = sum(Confirmed), Deaths = sum(Deaths), min_Deaths = min(Deaths)) %>%
  arrange(desc(min_Deaths)) %>%
  slice(1:10)

ggplot(data = top10d, mapping = aes(x = Country_Region, y = Confirmed)) + geom_point()
```

# Deaths for Top 10 States March 13, 2020

```{r}
top10d <- report_03_13_2020 %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarize(Confirmed= sum(Confirmed), Deaths = sum(Deaths), min_Deaths = min(Deaths)) %>%
  arrange(desc(min_Deaths)) %>%
  slice(1:10)

ggplot(data = top10d, mapping = aes(x = Deaths, y = Province_State)) + geom_bar(stat = "identity")
```



# Confirmed Cases for Top 10 States March 13, 2020
```{r}
top10d <- report_03_13_2020 %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarize(Confirmed= sum(Confirmed), Deaths = sum(Deaths), min_Deaths = min(Deaths)) %>%
  arrange(desc(min_Deaths)) %>%
  slice(1:10)

ggplot(data = top10d, mapping = aes(x = Confirmed, y = Province_State)) + geom_bar(stat = "identity")
```

